CREATE TABLE authors (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         full_name VARCHAR(120) NOT NULL,
                         birth_date DATE,
                         country VARCHAR(100),
                         biography VARCHAR(1000)
);

CREATE TABLE categories (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(80) NOT NULL,
                            description VARCHAR(255)
);

CREATE UNIQUE INDEX uk_categories_name_lower
    ON categories (LOWER(name));

CREATE TABLE readers (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         full_name VARCHAR(120) NOT NULL,
                         phone VARCHAR(255) NOT NULL,
                         email VARCHAR(255),
                         registered_at TIMESTAMP NOT NULL,
                         status VARCHAR(255) NOT NULL,

                         CONSTRAINT uk_readers_phone UNIQUE (phone)
);

CREATE TABLE books (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       isbn VARCHAR(20) NOT NULL,
                       title VARCHAR(200) NOT NULL,
                       author_id BIGINT NOT NULL,
                       category_id BIGINT NOT NULL,
                       published_year INTEGER NOT NULL,
                       total_copies INTEGER NOT NULL,
                       available_copies INTEGER NOT NULL,
                       status VARCHAR(255) NOT NULL,
                       created_at TIMESTAMP NOT NULL,

                       CONSTRAINT uk_books_isbn UNIQUE (isbn),

                       CONSTRAINT fk_books_author
                           FOREIGN KEY (author_id)
                               REFERENCES authors(id),

                       CONSTRAINT fk_books_category
                           FOREIGN KEY (category_id)
                               REFERENCES categories(id),

                       CONSTRAINT chk_books_total_copies
                           CHECK (total_copies >= 1),

                       CONSTRAINT chk_books_available_copies
                           CHECK (
                               available_copies >= 0
                                   AND available_copies <= total_copies
                               ),

                       CONSTRAINT chk_books_published_year
                           CHECK (published_year >= 1000)
);

CREATE TABLE loans (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       book_id BIGINT NOT NULL,
                       reader_id BIGINT NOT NULL,
                       borrowed_at TIMESTAMP NOT NULL,
                       due_date TIMESTAMP NOT NULL,
                       returned_at TIMESTAMP,
                       status VARCHAR(255) NOT NULL,

                       CONSTRAINT fk_loans_book
                           FOREIGN KEY (book_id)
                               REFERENCES books(id),

                       CONSTRAINT fk_loans_reader
                           FOREIGN KEY (reader_id)
                               REFERENCES readers(id)
);

CREATE INDEX idx_books_author_id
    ON books(author_id);

CREATE INDEX idx_books_category_id
    ON books(category_id);

CREATE INDEX idx_books_status
    ON books(status);

CREATE INDEX idx_loans_book_id
    ON loans(book_id);

CREATE INDEX idx_loans_reader_id
    ON loans(reader_id);

CREATE INDEX idx_loans_status
    ON loans(status);

CREATE INDEX idx_loans_due_date
    ON loans(due_date);

CREATE INDEX idx_readers_status
    ON readers(status);